### ISSUE TITLE
Chunked HTML Version for Website

### ISSUE THREAD

**Issue by tajmone** [Fossy-Cats/Git-Buch_EN#35]
Begin working on the chunked HTML book version for the website, in branch [`beta-dev-chunker`][beta-dev-chunker]:

- [x] Add to repo [asciidoctor-chunker] script.
    + [x] Tweak it to name chunked files "`Git-Book_`" instead of "`chap_`".
- [x] Rakefile:
    + [x] Tweak `publish` task to create new targets:
        * [x] `standalone` for a self-contained single file for download.
        * [x] `www` for website chunked version.
            - [x] **Fix chunks titles** — Add Ruby script to parse each chunked file, extract the Section title and inject it into `<title>`.
            - [x] Add `-a web-edition` attribute to Asciidoctor invocation options.
                + [x] **ADoc source** — Add conditional directives for `web-edition` attribute to show download link to stand-alone version in Preamble.
- [x] `README.md`:
    + [x] Revise and polish whole document.
- [x] `docs_src/README.md`:
    + [x] Fix all book links to new standalone HTML file: `/docs/download/Git-Book.html`
    + [x] Revise and polish whole document:
        * [x] Delete "Translation Status" section (moved to Issue #36).

[beta-dev-chunker]: https://github.com/Fossy-Cats/Git-Buch_EN/tree/beta-dev-chunker

[asciidoctor-chunker]: https://github.com/wshito/asciidoctor-chunker

**Comment by tajmone** [comment]
# Chunked Book Ready

@SicroAtGit, I've managed to tweak the chunker code to enforce a custom file naming convention in the generated chunks, and also to write the Ruby method to fix the chunks' `<title>` with the real Section title, instead of all docs showing the Book title.

There are still a number of small chore to do— (including adding a self-contained HTML book to the repository, so end users can download it, and linking it from the website main page, etc.

But for tonight I'm taking a break.

I'd like you're feedback on the chunked version, whether you like it or not. You can check the chunked docs in the `beta-dev-chunker`, locally, or online via the HTML Live Preview link:

- https://htmlpreview.github.io/?https://github.com/Fossy-Cats/Git-Buch_EN/blob/beta-dev-chunker/docs/index.html

Please give me some feedback before I finish the work, so that I know whether you're OK to merge it into `main` when it's finished.

**Comment by SicroAtGit** [comment]
I tried your link and found there that the sections could not be jumped to directly without first jumping to the appropriate page. For example, try to go directly to the _Who Is This Book Intended For?_ section without first going to the _Preface_ page.

In Firefox, I tried it again with a freshly created test profile in case my browser settings or add-ons triggered this, but no, the problem persisted.

After that I checked out your branch locally and called the local `index.html` file in Firefox. Everything works perfectly then.

Also, [the sample output](http://www.seinan-gu.ac.jp/~shito/asciidoctor/html_chunk/index.html) from the `asciidoctor-chunker` author does not have this problem.

So it must be a problem with the `htmlpreview.github.io` service. Shouldn't be a problem for us because we use GitHub Pages, but good to know that this problem exists.

Good job!

**Comment by tajmone** [comment]
> So it must be a problem with the htmlpreview.github.io service.

yes, because of the way **Live HTML Preview** service wraps contents inside a frame with redirection, which often breaks CSS and JS. 

In fact I wasn't sure if I should have provided the Live link, but it seems that everything was OK at first glance, so I thought it might spare you having to rebuild and all just for a quick glimpse. I didn't realize it affected the JS, I only checked the CSS.

**Comment by SicroAtGit** [comment]
No problem, the link served its purpose: I had a quick preview.

**Comment by tajmone** [comment]
# Standalone HTML Edition Ready

@SicroAtGit, I've updated the `Rakefile` to also publish a standalone version of the book, which users can download.

The generated file is in:

    /docs/download/Git-Book.html

i.e. inside the GHPage folder, so it can be also viewed online and saved, and at the same time we can offer a raw-GitHub link to download it from the repository home. 

I'll tweak the AsciiDoc sources to ensure that the online version (the "chunked book") will provide a download link which users can right click to "Save As..." as a means to download the standalone version directly from the website.

In the repository README, I'll add a raw-GH link instead.

Does it sound good to you? or could there be better solitions?

I think that having also the single-file version online can be helpful, e.g. when users need to search the book, since searching the chunked version is harder.

I've polished and optimized the `Rakefile` a lot, to make it more readable and self-explaining, dropping a few comments here and there to help Rake newbies, but also introduced new constants to allow quick changes of the toolchain through single definitions. Anyhow, let me know what you think of the new `Rakefile`.

There is still some work left to do, but I should be ready to squash by the weekend.

**Comment by SicroAtGit** [comment]
Looks very good!

**Comment by tajmone** [comment]
> Looks very good!

Yes, I'm quite pleased with it.

In the future I might try to implement the back/next navigation buttons as vertical bars on the sides of the main document, instead of having them at the page bottom, so the reader has access to them all the time. But I'll need to find where the chunker injects the navigation tags in the source project, since our modded version is based on the generated JS chunker, which means I'll have to handle that in a custom branch of asciidoctor-chunker — but then I could submit a PR for the change.

In the future asciidoctor-chunker is planning to introduce templates, which should allow some margin of customization of both the final HTML template and the CSS that goes with it. Once that feature is in place I'll like to contribute new CSS stylesheets to the project. But its development pace is fairly slow, since its maintainer is very busy.

Another fix I'll like to introduce is splitting the main title and subtitle on separate lines, like in the PDF backends. This should be achievable by adding custom HTML5 templates to the repository, using Haml or Slim, so it should be fairly easy.

**Comment by SicroAtGit** [comment]
> In the future I might try to implement the back/next navigation buttons as vertical bars on the sides of the main document, instead of having them at the page bottom, so the reader has access to them all the time.

I also had this thought when I saw the small arrows on the page bottom. Glad to hear you're thinking of implementing it.

> Another fix I'll like to introduce is splitting the main title and subtitle on separate lines, like in the PDF backends.

Ok, sounds good to me, although I can't really picture it right now.
